#!/bin/bash

my_function() {
    # Первый аргумент - файл вывода
    local output_file="$1"
    shift

    # Остальные аргументы - команда
    "$@" > "$output_file" 2>&1
}


function_name="$1"
shift

"$function_name" "$@"

