#!/bin/bash



# Переменные по умолчанию

longitude=""

latitude=""



# Используем getopts

while getopts "x:y:" opt; do

  case $opt in

    x)

      longitude="$OPTARG"

      ;;

    y)

      latitude="$OPTARG"

      ;;

    \?)

      echo "Использование: $0 -x <долгота> -y <широта>"

      exit 1

      ;;

  esac

done



# Получение погоды с сайта wttr.in

weather=$(curl -s "wttr.in/${longitude},${latitude}?format=%C+%t")



# Выводим результат

echo "Погода в точке (долгота: $longitude, широта: $latitude): $weather"
